### ISSUE TITLE
Sock-puppetry

### ISSUE THREAD

**Issue by AndrewCarterUK** [php-cds/php-cds#1]
Given the evidence that certain members of the PHP community are shallow enough to use fraudulent behaviour to achieve their goals (including fake GitHub accounts) - do you have any plans to mitigate this?

**Comment by marcj** [comment]
Isn't Github doing here already a good job in banning those guys? Also I think we can easily spot fake accounts. That's the nature of free votes, we should and will able to handle that.

**Comment by AndrewCarterUK** [comment]
I'm not sure, I'm sure more believable fake accounts could be created in smaller numbers and by somebody more intelligent.

But I'm only raising the question - I haven't got any better ideas!

**Comment by marcj** [comment]
That's something we just need to deal with. I don't think anyone is able to create thousand of realistic fake accounts. However, I'm a big believer in free votes - security or doubts about some percentages could be fake is a valid thought but I think that's the nature of free votes. You can not make it 100% safe.

**Comment by NoxiousPluK** [comment]
Once there is a certain momentum, small numbers of fake accounts can't have much influence.

It is a great question tho, especially during a start-up period. Maybe a minimum number of votes would be required?

**Comment by mario-deluna** [comment]
I think the effort needed to build a network of really believable Github bots won't match the need to get a PHP Community standard accepted. If there is no lobbyism involved and if there is no need to 
to prove yourself as popular project author, it would be probably much easier to just spend the time proposing something the community really wants..

I might be naive but I think bots won't be a problem here. Again also I still think it will be pretty easy to spot them..

**Comment by marcj** [comment]
Yeah the whole idea can only fly when we have enough momentum. If enough folks start voting and are aware of this project, this approach is actually able to work. So go out and spread the word :)

**Comment by sparkysan** [comment]
I think this is definitely worth a try, even if all it does is serve to get more people interested in contributing to community standards. I can't see any downsides to giving it a go and seeing how it works out!

**Comment by geggleto** [comment]
Really glad to see this pop up. PHP is very community driven, so it makes sense that a standards body is also community driven and not ruled over by a few people.

**Comment by scopefragger** [comment]
Agreed,  Its frustrating when the development is driven by but a few.

**Comment by geggleto** [comment]
There is still a lot of work that needs to be done to finalize the whole RFC -> Proposal -> Approval. How much time do we give people to vote on a Proposal, etc.

**Comment by boussou** [comment]
Fake accounts could be easily debunked

**Comment by dracony** [comment]
Really, Andrew, get a life!

Stop popping up everywhere throwing accusations at me. They locked the FIG thread and now you're just taking it everywhere else. I don't want to chase you all over internet to debunk your claims. And people see what you write and consider it common facts.

The entire topic is stupid. Who would create a bot network to get a particular standard in? There is literally no point in doing so, it's not even like it's personal fame like having a lot of github stars.

Voting by a community is stupid anyway, since the whole point of having FIG come out with standards was that FIG members are the ones actually implementing them. If some random community votes in a standard what incentive do I have to implement it?

**Comment by AndrewCarterUK** [comment]
@dracony - None of this post was directed at you, although your actions obviously inspired it.

The question is simply how do we protect against fraud in the community. It'd help everyone involved if you could debate the topic, and if you have any separate issues bring them up in a new post.

We're also not discussing you in this thread, that's been done. Now we're trying to learn the lessons and move forward.

**Comment by marcj** [comment]
@dracony, really, please stand back from making this offtopic as well or we need to remove your offtopic messages. That concern of @AndrewCarterUK in this issue is valid and we should consider it.

**Comment by dracony** [comment]
The actual solution is simple, I just posted in on reddit:

Allow only existing implementations to be standardized, it fixes the "who is going to actually build it?" problem and also provides a high threshold for filtering out random ideas with no backing.

On top of that you can easily require voters to have at least a year old account on the website. This combined with the treshold would fix everything

**Comment by AndrewCarterUK** [comment]
@dracony - How does that relate to low lifes trying to manipulate the result of votes with sock puppets?

**Comment by marcj** [comment]
> Voting by a community is stupid anyway, since the whole point of having FIG come out with standards was that FIG members are the ones actually implementing them. If some random community votes in a standard what incentive do I have to implement it?

We have in this repo already many supporter with well known projects. So I really don't see any problem with that. Its likely that those guys are going to adopt new recommendations.

**Comment by dracony** [comment]
because to have any gain from this you'd have to already have built an implementation. And once you spent so much effort having somebody accuse you of sockpuppeting wastes a lot of your hard work. Like you yourself have shown recently.

Now, if a person can just put a random idea in and send 30000 bots to vote for it, it's much easier.

**Comment by marcj** [comment]
> Now, if a person can just put a random idea in and send 30000 bots to vote for it, it's much easier.

It's not. You forgot how standards work. When votes indicate that a recommendation should be published, it doesn't become automatically a standard. When all major player decide to not adopt it, then it remains the definition of "recommendation". So, using 30k bots to vote is completely worthless. It's pretty a self-regulation.

> because to have any gain from this you'd have to already have built an implementation

See https://github.com/php-cds/php-cds/issues/1#issuecomment-218794856

**Comment by mario-deluna** [comment]
God damit, please stop the damn Drama...

Im really getting sick of it, it just points a huge "Kindergarten light" on the PHP community.. I won't contribute to a Group that behaves like that. This should be a discussion not a fight.

**Comment by marcj** [comment]
I agree. Locked for now. Regarding the reaction of the question from the author it appears that its a consensus here that fake accounts are not a problem.
