### ISSUE TITLE
[MOD] Application

### ISSUE THREAD

**Issue by geggleto** [php-cds/php-cds#18]
As an active member of the open source community, I would not mind taking on some additional responsibility with this group.

**Comment by matthewtrask** [comment]
As an active community member, I too, will volunteer helping out with whatever I can.

**Comment by benlipp** [comment]
I would also like to volunteer!

**Comment by marcj** [comment]
@geggleto is already active in other php communities and proved his trust, so very welcome! He is now part of the mods (although that should be really nothing special. We are just here to clean up the dirt 🛁  ♻️  ☁️ )

@rocketpastsix @obiwanakin feel free to query me in [gitter](https://gitter.im/php-cds/php-cds)
