### ISSUE TITLE
[RFC] Pageable interface

### ISSUE THREAD

**Issue by Addvilz** [php-cds/php-cds#21]
This RFC proposes an interface that could potentially be used to hold/retrieve and iterate via pageable collections. 

This could be rather useful for having a common interface across various storage backend libraries to retrieve pageable data - think comments, posts, items, things, you name it.

Other possible way was to have `setCurrentPage` and then determine the next and previous relatively to current, but that would limit ability to determine if page N has next or current page except for setting it as current, that could lead to ambiguity.

``` php
interface Pageable
{
    /**
     * @return int
     */
    public function getTotalPages();

    /**
     * @return int
     */
    public function getPageSize();

    /**
     * @param int $size
     * @return $this
     */
    public function setPageSize($size);

    /**
     * @param int $page
     * @return mixed
     */
    public function getPage($page);

    /**
     * @param int $page
     * @return bool
     */
    public function hasNextPage($page);

    /**
     * @param int $page
     * @return bool
     */
    public function hasPreviousPage($page);

    /**
     * @param int $page
     * @return bool
     */
    public function isValidPage($page);
}
```

**Comment by rask** [comment]
Do `hasNextFromPage` and `hasPreviousFromPage` stand for checks that a previous and next page instances exist? Could they work as `hasNextPage` and `hasPreviousPage` for simplicity?

**Comment by Addvilz** [comment]
I meant those checks as validating that next or previous page relative to `$page` exists, that's why I chose the long name. Perhaps that could be improved. Thanks!

**Comment by scopefragger** [comment]
Would there be le-way to alter the content that were paging,   for example if the array of pages suddenly grew?

**Comment by Addvilz** [comment]
That would be completely up to implementation, actually, however, the way I imagine it, `getTotalPages` must always return actual number of pages during the call. The state of Pageable is only constant for the time of invocation.

**Comment by tfrommen** [comment]
I'm missing something like `getNextPage()` and `getPreviousPage()` here. Or wouldn't that be part of an interface for implementations of pageable collections? I think it should.

And why:
- does `hasNext/PreviousPage()` an `int` argument?
- does `getPage()` return an `array`?

**Comment by Addvilz** [comment]
@tfrommen `hasNext` and `hasPrevious` without argument would imply you store current page in the Pageable itself. I was considering it, but because of this, you can't get `hasPrevious` or `hasNext` against a page you could calculate on consumer side. I have some doubts about that as well. Lets see what others think and perhaps its worth to change it like this.

As to `getPage`, nice catch, thats an error. It should be mixed. :) Thanks!

**Comment by nilportugues** [comment]
I'd advocate to go this way, it's based on Spring Framework and makes quite a lot of sense. 
- http://docs.spring.io/spring-data/data-commons/docs/current/api/org/springframework/data/domain/Pageable.html
- http://docs.spring.io/spring-data/data-commons/docs/current/api/org/springframework/data/domain/PageRequest.html

This means having 2 objects, Pageable and Page. 

I've done an implementation based on Spring's: 

Page goes for the page representation: https://github.com/PHPRepository/php-repository/blob/master/src/Domain/Model/Repository/Page.php

Pageable goes for the collection that can be paged: https://github.com/PHPRepository/php-repository/blob/master/src/Domain/Model/Repository/Pageable.php

**Comment by Addvilz** [comment]
@nilportugues Why does you pageable and page both have some sort of elements? Is there a reason to enforce fixed contents? If its a vertical structure, then Page should be consumable, but I specifically allowed for Page to be whatever (e.g. mixed). The Spring Page is actually Pageable you see here.

**Comment by nilportugues** [comment]
Pageable interface should allow you to fetch based on conditions and always return the same kind of object, a Page.

If we don't enforce a typing, in this case a Page, we cannot guarantee how this page can be used. A Page object should be a wrapper.

This reminds me of PSR6 and PSR7. A CacheItem (PSR6) or a Body (PSR7) act in the same way. 

These objects can contain anything, but are always returned and contain method/s to use or obtain the contained data.

**Comment by nilportugues** [comment]
@Addvilz I mean I'm perfectly fine with the proposed interface (ok, isValidPage is weird as we could have isLastPage and make use of hasNextPage) , but I'm missing a Page interface.

**Comment by Addvilz** [comment]
I don't believe wrapping all records that Pageable returns is a good, or performant idea. Imagine that Pageable as given here would be implemented by some sort of database interface that queries for particular entities. My idea about this was to have, for example, a repository implement this - it would make pageable lists much easier.

In this case, I would return the entity directly, you would wrap in an Page object. But Page interface still does not know and can not know what the entity class will be, so we still cant warrant correct use - the problem is just moved a little deeper in the tree. 

What I miss is generics in PHP :palm_tree: That would solve this issue quite nicely, but unfortunately, PHP is still dynamically typed.

**Comment by nilportugues** [comment]
@Addvilz I agree on your points, and we're on the same page (pun intended).  But because the lack of generics.. is the reason I'm proposing the wrapper. 

Besides that, a Page only makes sense in a context, so it requires having some logic such as:
- `public function hasPrevious()`
- `public function isFirst()`
- `public function isLast()`
- `public function hasNext()`
- `public function pageNumber()`
- `public function pageSize()` //last page does not need to have same size as first, for instance.
- `public function totalPages()`

**Comment by Addvilz** [comment]
Yeah, I think I finally understand what you mean. Perhaps this demo implementation can shed some light:

``` php

class PageablePostRepository implements Pageable
{
    private $queryBuilder;

    private $pageSize = 10;

    public function getTotalPages()
    {
        return $this->queryBuilder->count();
    }

    public function getPageSize()
    {
        return $this->pageSize;
    }

    public function setPageSize($size)
    {
        $this->pageSize = $size;
        return $this;
    }

    /**
     * @param int $page
     * @return \Some\Entity\Class
     */
    public function getPage($page)
    {
        return $this->queryBuilder->offset($page * $this->pageSize)->findOne();
    }

    public function hasNextPage($page)
    {
        return ($page + 1) <= $this->getTotalPages();
    }

    public function hasPreviousPage($page)
    {
        return ($page - 1) >= $this->getTotalPages();
    }

    public function isValidPage($page)
    {
        if ($page >= 1) {
            return true;
        }

        return $page <= $this->getTotalPages();
    }
}
```

**Comment by shadowhand** [comment]
This suggestion only works for known page sizes, which is not always feasible in large systems that are aggregating data from disparate sources. I would like to see an additional interface that addresses paging based purely on offsets, either as part of this recommendation or as a separate recommendation.

**Comment by Addvilz** [comment]
@shadowhand do you have some code sample in mind on how you think that should work? I like the idea. Perhaps not as same interface, but definitely worth investigating.

**Comment by Addvilz** [comment]
... on the other hand, I am not sure how having increasing number of pages affects this? You set the page size yourself. In what scenario the page size is dependent on total number of pages?

**Comment by moufmouf** [comment]
Hey guys,

Just out of curiosity, did you know that @beberlei already worked on such an interface?

Here: https://github.com/beberlei/porpaginas

It is already solid and used by many. Maybe a good idea would be to ask him some feedback or simply use his work (I've been implementing the interface, it is well designed and rock solid)

**Comment by syrm** [comment]
This standard is not useful in my opinion.

**Comment by krzysiekpiasecki** [comment]
We have Iterator interface and implementations. I agree with @oxman.

**Comment by Addvilz** [comment]
How does Iterator interface solves this problem?

**Comment by krzysiekpiasecki** [comment]
You can iterate what you want. You can always implement list value handler based on iterators.

**Comment by Addvilz** [comment]
Withdrawn then
