### ISSUE TITLE
[VOTING] [RFC] Length of voting period

### ISSUE THREAD

**Issue by geggleto** [php-cds/php-cds#27]
This RFC will determine the length of the voting period.

2 Weeks - Vote Here: https://github.com/php-cds/php-cds/issues/27#issuecomment-219127515
1 Week - Vote Here: https://github.com/php-cds/php-cds/issues/27#issuecomment-219127532
1 Month -Vote Here: https://github.com/php-cds/php-cds/issues/27#issuecomment-219127546

Please add any other time-intervals to this thread, there are just some I came up with.

**The vote will be terminated on 27.05.2016 21:00 MESZ**

**Comment by geggleto** [comment]
2 Weeks

**Comment by geggleto** [comment]
1 Week

**Comment by geggleto** [comment]
1 Month

**Comment by xyNNN** [comment]
In this RFC we vote for the standard length of the voting period for voting a RFC, cool - but how long this vote will be? 😄  We could commit us to the default voting period of 2 weeks from the initial idea from @marcj

**Comment by peter-mw** [comment]
@xyNNN  maybe 1 month at least :)

**Comment by geggleto** [comment]
@xyNNN I had figured it would be defaulted to 2 weeks until this passes ;)

**Comment by OddGreg** [comment]
I voted for 1 month mainly because life has a way of throwing up obstacles, and I think 4 weeks allows for a number of eventualities.

**Comment by marcj** [comment]
Let's use 2 weeks for this vote here as that's the initial value. We could held a vote later when we see many complains about a too short voting length

**Comment by naroga** [comment]
PLEASE, stop voting on things right away. Let people discuss the issues before reacting.

This should be a discussion-only issue, and an actual voting issue should be opened in a few days/weeks.

**Comment by marcj** [comment]
@naroga you are actually completely right. :) However, I guess with the voting length as topic its not so dramatic. We could add another vote when there are other opinion's pop up.

**Comment by naroga** [comment]
@marcj, I just opened my github and there were 3 new issues being voted on. I feel like people are in a huge rush to get things going. Doing too much, thinking too little. No busy framework/library author has the time to read all those issues, think about them and vote in less than a week. And votes are already being counted.

If this community wants actual developers here, give the actual developers time to participate.

**Comment by marcj** [comment]
@naroga please don't [cross post](https://github.com/php-cds/php-cds/issues/28#issuecomment-219150323). That's hard to track.

As already said: There is no active vote on a PSR or something that needs long consideration time.

**Comment by danielgsims** [comment]
I think 1 month would be best. Often folks might head on vacation for two weeks and disconnect from the world. One month would be sufficient to for those people to check back in.

**Comment by minhd** [comment]
Voting for an issue can have a lasting effect that would echo out through the PHP community. Needs careful consideration and as many people voting as possible. Rather than have shotgun voting for big issues and long drawn out flame wars for trivial issues. Would it be better to have the voting period cater to the size of the issue instead?

**Comment by kobykorman** [comment]
For the same aforementioned reasons, I believe 1 month is the proper _minimum_ for voting.

**Comment by KyleWiering** [comment]
Two weeks for rudimentary things, don't keep things permanently set in stone like FIG. Be more agile. The reason for the 1 month is that someone's perspective gets missed. Alright, so the use case is 2 weeks missed a perspective - if it is that important, make a motion on the "missed" perspective - get that voted on. Please don't implement the U.S. Senate. For example, new discussion on this topic pretty much stopped within 4 days.  (And I'm mostly just re-iterating a previous comment!)

**Comment by danielgsims** [comment]
...more agile?

![](http://66.media.tumblr.com/7c07d68e3312790e89c8ae0e002980d6/tumblr_n54bjpm0Ex1qbpgqvo1_1280.jpg)

**Comment by xyNNN** [comment]
Voting ended. Period of 1 month won. 🎉 Issue has been lock, so you can see all final votes on their comments.
