### ISSUE TITLE
How about using online voting system for RFC's?

### ISSUE THREAD

**Issue by odan** [php-cds/php-cds#29]
http://doodle.com/poll/483ufyhzrd3aqz4p

**Comment by marcj** [comment]
Doodle is very easy to fake.

**Comment by xyNNN** [comment]
As @marcj mentioned it's easy to fake the voting and on the other side we increment the tool chain and make it more complex then it is. GitHub provides us all functionality which we need to create community-driven standards.

**Comment by geggleto** [comment]
@odan I would prefer to have something that tied into GitHub using the OAuth.

**Comment by odan** [comment]
@geggleto I agree. There should be an integrated github voting system like doodle.

**Comment by marcj** [comment]
Having a dedicated service/website where people can vote only with GitHub authentication is actually a pretty good idea. Maybe with a markdown/image-generation which could be placed in the thread at the beginning so people see immediately how many votes +/- and what the voting link is.

**Comment by odan** [comment]
@marcj Sounds great!

**Comment by xyNNN** [comment]
Yeah, it could be a good idea. But on the beginning I would prefer the pragmatic way and use the functionality from GitHub via GitHub reactions. After a while we could sum up and see if a dedicated service is needed or not.

**Comment by peter-mw** [comment]
+1 voting on github is ok for now

**Comment by geggleto** [comment]
We will totally re-evaluate it in a couple of months... Currently there are so many things that need our attention!

**Comment by odan** [comment]
Ok great, thanks!

**Comment by OddGreg** [comment]
@marcj: I'm in agreement. Considering that we are all quite capable of putting together a relatively simple site (that uses github for authorization) probably isn't much work. Mind you, we are notorious for not creating sites for ourselves. At least I'm not. Actual work gets in the way.
