### ISSUE TITLE
[RFC] Session Server Request interface

### ISSUE THREAD

**Issue by geggleto** [php-cds/php-cds#3]
The current implementation of PSR-7 really lacks some core items.

Notably at least for me, I have found issues with:
- Session Management

In other libraries and languages [ex. expressjs], a session should/is be attached to the request object in a read-only manner. Populating the Request object can happen as a middleware in a rather trivial way but I would be open to making the middleware apart of this RFC.

We should include these new methods on the ServerRequestInterface

``` php
public function getSession(); //returns the entire session array
public function getSessionElement(string $name);

public function setSession(array $session); //Replaces entire session store
```

**Comment by mario-deluna** [comment]
> ``` php
> public function withSession(array $session); //Replaces entire session store
> ```

When replacing the  entire session store, is the term `with` not a little bit misleading? For me it sounds like constructing a new Request object with the given session. I would suggest making it just a simple `setSession`.

**Comment by icambridge** [comment]
Wouldn't it be wiser to create a new interface for these methods than adding them on to the existing interface. Since people who don't require this functionality would have to implement it, this would breach Interface Segregation Principal no?

**Comment by geggleto** [comment]
@mario-deluna it's following the current PSR-7 guideline... I mean if we want to change it all then so be it, but given that I contribute regularly to a project that follows PSR-7 I would prefer to not change it much since there is already wide adoption of PSR-7.

@icambridge yes we would need to extend the existing interface. This would add the ability for users to use already existing PSR-7 projects as well.

**Comment by AndrewCarterUK** [comment]
I think this is the wrong way around, considering SRP.

I prefer:

``` php
$session = $sessionManager->getSession($request);
```

What you really want is a session manager.

**Comment by geggleto** [comment]
@AndrewCarterUK so how exactly do we populate session stuff into `$request` as currently there is no way for this to happen.

**Comment by AndrewCarterUK** [comment]
``` php
$session = $sessionManager->getSession($request);

$session->set('foo', 'bar');
// ...

$response = $session->tagResponse($response);

$sessionManager->persist($session);
```

**Comment by shadowhand** [comment]
HTTP spec does not mention sessions, therefore it is not included in PSR-7. There are plenty of middleware that already provide session management. It is not the job of the request/response objects.

**Comment by icambridge** [comment]
@geggleto Why extend, when we can just have a separate interface `SessionableServerRequestInterface` which we can implement. That way if people want to extend things further and maybe eventually move away completely from the original interface they can and aren't coupled to it?

**Comment by geggleto** [comment]
@icambridge that's not a half bad idea.

**Comment by shadowhand** [comment]
I don't see the point. Sessions are not in HTTP spec. Why not use an existing middleware?

**Comment by marcj** [comment]
I don't think you should stick to the HTTP spec. Only because Http doesn't contain session in the spec doesn't mean its not extremely handy.

**Comment by AndrewCarterUK** [comment]
It's confusing two different concepts.

If you extend PSR-7 to PSR-7.1 you immediately invalidate any library that doesn't update to this from working it. Aside, it's not even /your/ project to actually increase the version number on. It's a FIG standard, and it's theirs to version.

None of what is being proposed here requires a modification to PSR-7. PSR-7 offers a complete representation of HTTP messages - this is a separate component, a 'session manager'.

**Comment by marcj** [comment]
@AndrewCarterUK totally agree. We really shouldn't modify foreign PSRs. Having one beside that is ok, but I highly doubt it will ever be adopted, because PSR7 is actually already pretty good.

**Comment by e-stankevicius** [comment]
@marcj But then you have to think about other possible sessions. Maybe someone will want implement TCP fake sessions or etc. There are many types of session, so having one interface for them all not 
really makes any sense. In other hand having http request and response interfaces does make sense.

And session interface should be left for frameworks.

**Comment by shadowhand** [comment]
[Equip has a SessionInterface](https://github.com/equip/session/blob/master/src/SessionInterface.php) that could be useful here.

**Comment by e-stankevicius** [comment]
@shadowhand Come on. At least don't be asshole.

**Comment by shadowhand** [comment]
@bunnyholder Excuse me? Where was I being an asshole?

**Comment by geggleto** [comment]
@shadowhand I had not seen that before. I will have to look at it :)

**Comment by g0ddish** [comment]
@BunnyHolder way to keep it civil
