### ISSUE TITLE
[VOTING] [RFC] PHP-CDS Namespace

### ISSUE THREAD

**Issue by geggleto** [php-cds/php-cds#4]
Suggestions for Namespace names for our RFCs.

Please leave one per comment.

List of options.
`\Pcs` - Vote here: https://github.com/php-cds/php-cds/issues/4#issuecomment-218753253
`\Csr` - Vote here: https://github.com/php-cds/php-cds/issues/4#issuecomment-218803902
`\Cds` - Vote here: https://github.com/php-cds/php-cds/issues/4#issuecomment-218742503
`\Pcr` - Vote here: https://github.com/php-cds/php-cds/issues/4#issuecomment-218811437

**The vote will be terminated on 26.05.2016 14:30 MESZ**

**Comment by marcj** [comment]
Actually, we could just use `\Cds` which stands like the whole concept for `community driven standard`.
However, I also like `\Psr` because it included recommendation (because in the end, its only a recommendation, and only becomes a standard when enough people are using it)

**Comment by mario-deluna** [comment]
It think it really doesn't matter much but personally I feel more comfortable with `\Psr`.

**Comment by AndrewCarterUK** [comment]
The whole point of namespaces is to avoid a collision, hijacking `Psr` isn't a great idea as the FIG is actively using that namespace.

**Comment by AndrewCarterUK** [comment]
PHP Community Standards (PCS) would solve a lot of complications.

**Comment by jonnybarnes** [comment]
@AndrewCarterUK you mean `\Pcs`?

**Comment by AndrewCarterUK** [comment]
That or something similar.

**Comment by lfkeitel** [comment]
My vote would be for `\Pcs`. Less confusion that way.

**Comment by e-stankevicius** [comment]
So community named "PHP - Community Driven Standarts", makes "PHP Community Standarts".
Well, it really does make sense.
I'm with `\Pcs`

**Comment by geggleto** [comment]
@BunnyHolder @lfkeitel  plz thumbs up https://github.com/php-cds/php-cds/issues/4#issuecomment-218753253 :)

**Comment by sandermarechal** [comment]
There are other options possible. How about \Csr (for Community Standards Recommendation)?

**Comment by sfengyuan** [comment]
@sandermarechal  I'll go with this. Since Pcs makes me thinking  'microsoft' and Cds 'terminal command'

**Comment by marcj** [comment]
@sandermarechal I really like that too :)

**Comment by navarr** [comment]
\Csr is good.  I think \Pcr could also be good "PHP Community Recommendation"

**Comment by geggleto** [comment]
@sandermarechal I will keep updating the top post as new options become available :)

**Comment by OddGreg** [comment]
\Pcs or \Cds work for me, even though they both mean something different to me. I'm conflicted. 
Neither \Pcr or \Csr work for me, but I'll go with the flow.

**Comment by kilgaloon** [comment]
+1 `\Pcs`

**Comment by joecampo** [comment]
I like `\Pcs` the most. I don't like `\Csr` as every time I look at it I think `Customer Service Representative`

**Comment by rzeczkowskip** [comment]
`\Pcr` +1

**Comment by tfrommen** [comment]
_PHP Community Standards_, and thus `\Pcs`, is straight to the point. So :+1: on that.

**Comment by naroga** [comment]
@geggleto, this format is not really good. People come here at the start of the discussion, they 'react' to a post they like before giving it any kind of serious consideration (and even before any serious considerations have been made) and when the voting period actually starts, there are a lot of already-casted votes.

Every issue should be opened as a discussion, and a second issue should be opened for voting on the same subject.

**Comment by naroga** [comment]
Also, this format allows people to vote on multiple options, which I'm not sure is desirable.

There should also be a minimum discussion period on any subject.

**Comment by marcj** [comment]
> Also, this format allows people to vote on multiple options, which I'm not sure is desirable.

Not explicitly desirable, but it doesn't harm. If someone wants to vote on two options then this is perfectly fine. If they vote on all options, then its like they didn't vote at all in the end. :)

**Comment by OddGreg** [comment]
@naroga 

> when the voting period actually starts, there are a lot of already-casted votes.

I consider those 'votes' as upticks of approval of an idea rather than a final vote for adoption. Actual voting would be separate.

**Comment by naroga** [comment]
@OddGreg, I agree with you that this should be the case, but this is actually already under vote (I don't know why so hasty), and the official instructions on the original post tell people to vote by reacting positively to the comments in this very same thread.

**Comment by geggleto** [comment]
@OddGreg in the base readme, a proposal should be opened on the php-cds-psr for final voting.

**Comment by marcj** [comment]
> @OddGreg in the base readme, a proposal should be opened on the php-cds-psr for final voting.

For PSRs only.

**Comment by OddGreg** [comment]
@naroga: Ah. Good point.
@geggleto: Yes, I understand that.

**Comment by geggleto** [comment]
I know things are going pretty fast, but these are some pretty basic stuff that we should be able to come to a consensus on. If any1 has any other options they are more than welcome to add to the options.

**Comment by OddGreg** [comment]
@geggleto: That's a good point. I wonder if open voting duration should be based on the nature of the item on which we vote. ie: namespace may not require much time while a specification would. In my view.

**Comment by geggleto** [comment]
I think for the basic stuff, We are going to do 2 weeks. I realize that it does seem quick... but lets face it... 2 days ago this didn't exist and now over 260 people have starred this project with over 80 people watching it actively. The discussions that have been generated have been very positive. We need some basic stuff figured out quickly.

**Comment by matthewtrask** [comment]
@geggleto Its time to extract ideas and get them into read me's for others to read and check out.

**Comment by Exadra37** [comment]
Why all the proposals have only 3 letters on the namespace... `PCDS` will be better as it stands for the initials of **P**hp **C**ommunity **D**riven **S**tandards that is what we are trying to achieve :)

**Comment by itsjavi** [comment]
@Exadra37 PHP in the namespace is redundant since we actually are using PHP code for writing the standards themselves.

**Comment by Exadra37** [comment]
@mjolnic i said to use `Pcds` as all other proposal that start with `P` letter also stand for `PHP` and as i said stands for the initials of what we are trying to achieve

**Comment by naroga** [comment]
Just for the record: this voting ends tomorrow.

Andrew's suggestion for "PCS" was voted for 13 days. Exadra's suggestion for PCDS has only been up for voting for the past 6 days.

This is what you get when you have a vote in the same issue as the discussion.

**Comment by xyNNN** [comment]
Thank you @naroga!

I think we should try to be a bit more agile. A process wasn't never directly defined perfect at the beginning. Let us improve this together, step by step, community-driven :)

**Comment by marcj** [comment]
Voting ended. Namespace `\Pcs` won. :tada: Issue has been lock, so you can see all final votes on their comments.
