### ISSUE TITLE
Providing reference implementation

### ISSUE THREAD

**Issue by boussou** [php-cds/php-cds#8]
further to https://github.com/php-cds/php-cds/issues/1#issuecomment-218788455

@dracony _"Voting by a community is stupid anyway, since the whole point of having FIG come out with standards was that FIG members are the ones actually implementing them. "_

IMHO this is a good point. & I agree with you.
Then I think that maybe this new community php-cds would need to commit on providing a reference implementation (outside Phppixie, symfony or laravel),

**Comment by boussou** [comment]
plus I am already upset by people having the ability to decide who can talk (by closing topics while I was wrtiting the above answer).

**Comment by marcj** [comment]
There is no "need" to provide a actual implementation, but it's desirable. However I think as I stated in the other post that this is likely be the case. What's your actual question on this?

> I am already upset by people having the ability to decide who can talk (by closing topics while I was wrtiting the above answer).

The whole topic was about fake accounts, which has been answered. `ability to decide who can talk` Nobody forbids you to talk. You are free to open as many issues as you want, but please respect that topics that has been answered can be closed, especially when its going to be offtopic (like in this particular case). This is like in the real world. Its perfectly fine to create another issue with your raised question, so I don't see any issue here. :-)

**Comment by boussou** [comment]
About the above: Ok.
the topic was about fake accounts - and I think was useless at this stage.

> What's your actual question on this?

@dracony claimed that "FIG was relevant because the FIG members are the ones actually implementing them." 

**I think he is right,** and useless infinite discussion could happen quickly. To prevent  this it would be  relevant to discuss on/from actual source codes. Interfaces! Since we're on git it is easy.

so the question is: do you think it is relevant to provide a reference implementation for each?

**Comment by marcj** [comment]
Yeah, definitely relevant 👍

**Comment by dracony** [comment]
Also if you really want this idea to fly find people working on existing
psr proposals and suggest them moving them here and start work immediately.
Otherwise everybody will forget about it in a week
